// <auto-generated />
using System;
using BackendTechnicalAssetsManagement.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendTechnicalAssetsManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251029081716_AddStatusToArchiveItems")]
    partial class AddStatusToArchiveItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ArchiveItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("ArchiveLentItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OriginalUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserRole")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArchiveUsers");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0aa32eec-ccae-4bdf-b196-ba61592a40e0"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 29, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7377),
                            Description = "High-performance laptop for video editing.",
                            ItemMake = "Dell",
                            ItemModel = "XPS 15 9510",
                            ItemName = "Dell XPS 15 Laptop",
                            ItemType = "Laptop",
                            SerialNumber = "SN-LP-DELL-001",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 29, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7377)
                        },
                        new
                        {
                            Id = new Guid("824b66e7-c87d-40ea-8817-aa68fc511f34"),
                            Category = "MediaEquipment",
                            Condition = "New",
                            CreatedAt = new DateTime(2025, 10, 29, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7391),
                            Description = "1080p projector for classroom presentations.",
                            ItemMake = "Epson",
                            ItemModel = "HC 2250",
                            ItemName = "Epson Home Cinema Projector",
                            ItemType = "Projector",
                            SerialNumber = "SN-PR-EPS-002",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 29, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7392)
                        },
                        new
                        {
                            Id = new Guid("aed5cfb0-c7ed-4605-8da7-9fe0844ebe18"),
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 29, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7397),
                            Description = "Full-frame mirrorless camera with 4K video.",
                            ItemMake = "Canon",
                            ItemModel = "EOS R6",
                            ItemName = "Canon EOS R6 Camera",
                            ItemType = "Camera",
                            SerialNumber = "SN-CM-CAN-003",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 29, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7398)
                        },
                        new
                        {
                            Id = new Guid("4297ba1a-bfa5-4797-bd20-338968e98cbc"),
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 29, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7401),
                            Description = "Dynamic microphone for vocal recording.",
                            ItemMake = "Shure",
                            ItemModel = "SM7B",
                            ItemName = "Shure SM7B Microphone",
                            ItemType = "Microphone",
                            SerialNumber = "SN-MC-SHR-004",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 29, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7401)
                        },
                        new
                        {
                            Id = new Guid("3a362320-4f1c-4e1e-9663-8dcf00a420be"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 29, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7404),
                            Description = "Tablet for digital art and design classes.",
                            ItemMake = "Apple",
                            ItemModel = "iPad Pro 12.9-inch",
                            ItemName = "Apple iPad Pro",
                            ItemType = "Tablet",
                            SerialNumber = "SN-TB-APL-005",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 29, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7405)
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("LentItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49c32820-b057-464d-b458-9af448cd935e"),
                            BorrowerFullName = "John Doe",
                            BorrowerRole = "Student",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("0aa32eec-ccae-4bdf-b196-ba61592a40e0"),
                            ItemName = "Dell XPS 15 Laptop",
                            LentAt = new DateTime(2025, 10, 24, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7878),
                            Room = "",
                            Status = "Borrowed",
                            StudentIdNumber = "S2021-001",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "Alice Williams",
                            TeacherId = new Guid("b460ef0f-b121-4254-adc3-fe4b61e2069b"),
                            UserId = new Guid("8ea9bc1f-5958-4116-a9b1-f95a84247d70")
                        },
                        new
                        {
                            Id = new Guid("e8e98c2c-6001-4e51-a191-2268f7a31b76"),
                            BorrowerFullName = "Jane Smith",
                            BorrowerRole = "Student",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("aed5cfb0-c7ed-4605-8da7-9fe0844ebe18"),
                            ItemName = "Canon EOS R6 Camera",
                            LentAt = new DateTime(2025, 10, 19, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7892),
                            ReturnedAt = new DateTime(2025, 10, 27, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7892),
                            Room = "",
                            Status = "Returned",
                            StudentIdNumber = "S2021-002",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "Bob Brown",
                            TeacherId = new Guid("39ed3dca-ed06-40da-9218-d9f7e74d2c1b"),
                            UserId = new Guid("5545c15d-4c37-4e8c-a7b4-433c4e2296b1")
                        },
                        new
                        {
                            Id = new Guid("c49d4c58-a4c5-4c99-b007-41dda86c7b9d"),
                            BorrowerFullName = "Peter Jones",
                            BorrowerRole = "Student",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("824b66e7-c87d-40ea-8817-aa68fc511f34"),
                            ItemName = "Epson Home Cinema Projector",
                            LentAt = new DateTime(2025, 10, 28, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7906),
                            Room = "",
                            Status = "Borrowed",
                            StudentIdNumber = "S2021-003",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "Alice Williams",
                            TeacherId = new Guid("b460ef0f-b121-4254-adc3-fe4b61e2069b"),
                            UserId = new Guid("c38ac878-fd3e-4e0e-98b7-e6e9633332d8")
                        },
                        new
                        {
                            Id = new Guid("96983a71-0078-4344-bab7-38f3c26e539f"),
                            BorrowerFullName = "Alice Williams",
                            BorrowerRole = "Teacher",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("4297ba1a-bfa5-4797-bd20-338968e98cbc"),
                            ItemName = "Shure SM7B Microphone",
                            LentAt = new DateTime(2025, 10, 26, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7911),
                            Room = "",
                            Status = "Borrowed",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "",
                            UserId = new Guid("b460ef0f-b121-4254-adc3-fe4b61e2069b")
                        },
                        new
                        {
                            Id = new Guid("3659fa18-8fd9-4f81-be2f-56f43abc0f64"),
                            BorrowerFullName = "Bob Brown",
                            BorrowerRole = "Teacher",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("3a362320-4f1c-4e1e-9663-8dcf00a420be"),
                            ItemName = "Apple iPad Pro",
                            LentAt = new DateTime(2025, 9, 29, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7922),
                            ReturnedAt = new DateTime(2025, 10, 14, 8, 17, 16, 282, DateTimeKind.Utc).AddTicks(7923),
                            Room = "",
                            Status = "Returned",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "",
                            UserId = new Guid("39ed3dca-ed06-40da-9218-d9f7e74d2c1b")
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("f672bcd6-edbc-4f30-93a8-13e7212c8cb0"),
                            Email = "superadmin@example.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "$2a$11$y/VkxEowl/GwGC2rfwFdO.OrF3mCw82CsqWLDeiWvS6zbEPIr6ltS",
                            Status = "Offline",
                            UserRole = "SuperAdmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = new Guid("cbb71cad-8415-47e4-ad38-e82ec08d848e"),
                            Email = "admin1@example.com",
                            FirstName = "Admin1",
                            LastName = "User",
                            PasswordHash = "$2a$11$0chqINaXyJ7iBoN04u6o3.Z6l3aAMNStYxs4NjFL31tvLO9YwKIX2",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = new Guid("34f28ca7-2fd2-474f-b79b-1138d9b3b9ed"),
                            Email = "admin2@example.com",
                            FirstName = "Admin2",
                            LastName = "User",
                            PasswordHash = "$2a$11$MgWkYfE4yFAksG8axn29guSkbBLaLHBgBOkeyUvcT.OPMlXsV0h5.",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = new Guid("575b93d2-f029-484c-a93c-14cedde82491"),
                            Email = "admin3@example.com",
                            FirstName = "Admin3",
                            LastName = "User",
                            PasswordHash = "$2a$11$4xjkOJmUkrX/YfDxX5bWDu3aFOwRBdm548JPDwHSlT323Efv09cR6",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin3"
                        },
                        new
                        {
                            Id = new Guid("096ec110-8aac-423b-ba61-84e7c7d7f223"),
                            Email = "admin4@example.com",
                            FirstName = "Admin4",
                            LastName = "User",
                            PasswordHash = "$2a$11$oEgWWQN3T8qCkIb5q7Q3/e4UL/xt52lhDUiB0IiN80LojbTUShNw6",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin4"
                        },
                        new
                        {
                            Id = new Guid("0c54d6dc-fc42-4e58-b91b-a9d698ca0c45"),
                            Email = "admin5@example.com",
                            FirstName = "Admin5",
                            LastName = "User",
                            PasswordHash = "$2a$11$05Vg5.d1zlkhSQEQvRiT7e5ExStubgyDt/YyW4YjPRx1Iy5ITCHvm",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin5"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveStaff", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CityMunicipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveStudents", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveTeachers", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("472077a8-57f9-4055-8484-2a991ec2474f"),
                            Email = "staff1@example.com",
                            FirstName = "Staff1",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$lk9L9pL/wd3OGjly.isF1.hIwwKFln7q/smAqp9AeVzUX8Ux/I5XK",
                            PhoneNumber = "0998176543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff1",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("761c0790-26ad-4831-acac-4482b7556c72"),
                            Email = "staff2@example.com",
                            FirstName = "Staff2",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$qGF17gV8OBDSXCreyj3XlONRAYAfzlEL3VzLE4B2V2V5w7kHV14o6",
                            PhoneNumber = "0998276543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff2",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("5efc9101-d4e8-4fd2-b596-931cb122d508"),
                            Email = "staff3@example.com",
                            FirstName = "Staff3",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$gF9o.3PH5AUUlZ2Duo3iausstjJD1.ypMgSCLOaVV.KRSHIJh1GLy",
                            PhoneNumber = "0998376543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff3",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("97621ca9-3be8-42b2-8906-5fc04bfcc2ac"),
                            Email = "staff4@example.com",
                            FirstName = "Staff4",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$GjjLdw.GpdM1zp7XCkdHpOVtHMIttoPYcnVoIcEh3DfDXKw350t/6",
                            PhoneNumber = "0998476543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff4",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("8ae7fa41-e6b5-419c-808b-38939bc44bdc"),
                            Email = "staff5@example.com",
                            FirstName = "Staff5",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$epNS/vX2DO/1ZlHt3raAdeK3E1y5UzvRHNVxdDuw8LIYPOAz5eQEi",
                            PhoneNumber = "0998576543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff5",
                            Position = "Lab Technician"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("StudentIdNumber")
                        .IsUnique()
                        .HasFilter("([StudentIdNumber] IS NOT NULL AND [StudentIdNumber] <> '')");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ea9bc1f-5958-4116-a9b1-f95a84247d70"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$OFmMAx4xfCuts1DEM3nWiOULMma3nt669xmWdjsj2oLW8cnWkfDJy",
                            PhoneNumber = "0912134567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "johndoe",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "S2021-001",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("5545c15d-4c37-4e8c-a7b4-433c4e2296b1"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$2Lcl8ZlwDzGoSfWfziD6H.G07V8iz8o3verDvgRwzKDyDoXc7vMUe",
                            PhoneNumber = "0912234567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "janesmith",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "S2021-002",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("c38ac878-fd3e-4e0e-98b7-e6e9633332d8"),
                            Email = "peter.jones@example.com",
                            FirstName = "Peter",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$/ZJ1qZWJAC2amV/RP/WFh.kpyymcfWCtjAVBKSo20XwiX7Q.7e0HK",
                            PhoneNumber = "0912334567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "peterjones",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "S2021-003",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("1bbca5bc-adec-417a-aea2-0b6046fccb08"),
                            Email = "student4@example.com",
                            FirstName = "Student4",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$LD81DYBJ.hlzJOExa4U5cO2TjRiU5BDqnmKkxHetfXEgRCUXGIGHK",
                            PhoneNumber = "0912434567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student4",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "2023-0004",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("abc42ee5-6dc9-40b3-b0a7-b34dcea136dc"),
                            Email = "student5@example.com",
                            FirstName = "Student5",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$TLDKTh5LDvOBAXH6ky1.xucDCOPMlhLreM8mhPNaEcf6jVdUpN5ly",
                            PhoneNumber = "0912534567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student5",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "2023-0005",
                            Year = "3"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b460ef0f-b121-4254-adc3-fe4b61e2069b"),
                            Email = "alice.williams@example.com",
                            FirstName = "Alice",
                            LastName = "Williams",
                            PasswordHash = "$2a$11$qn/qfQ1vsykrAMN0BTMji.npSBt4HfCnpl1eMlaPQrx0xIyQ4n.l6",
                            PhoneNumber = "0917123456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "alicewilliams",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("39ed3dca-ed06-40da-9218-d9f7e74d2c1b"),
                            Email = "bob.brown@example.com",
                            FirstName = "Bob",
                            LastName = "Brown",
                            PasswordHash = "$2a$11$E..P1oE9qtd3yILx69FMx.NU.fMTV48jLJGfKYWDwLR7fj/gFjhRa",
                            PhoneNumber = "0917223456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "bobbrown",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("b98d57dd-6c71-4041-be81-2e3496c109c8"),
                            Email = "teacher3@example.com",
                            FirstName = "Teacher3",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$0mtEUQNgzH9Fons9jBT/bOCBY02LQygTijXZ1oSeIbOf/pDbp9hWW",
                            PhoneNumber = "0917323456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher3",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("2566b03b-481f-4218-a816-b160e2246b7b"),
                            Email = "teacher4@example.com",
                            FirstName = "Teacher4",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$kYQ6zeRIXuqllK6S8ezEcehQfJBhOLyrDu/p4dwJfwBIxn8rU5tEq",
                            PhoneNumber = "0917423456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher4",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("59c31cfe-094e-4610-87e1-b21b45710e22"),
                            Email = "teacher5@example.com",
                            FirstName = "Teacher5",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$A.hVMV0jQzNDcmaKlJGtg./rLiH5blZIVnIsxiX8pyGz/xIj/naby",
                            PhoneNumber = "0917523456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher5",
                            Department = "Information Technology"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("LentItems")
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Staff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Navigation("LentItems");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
