// <auto-generated />
using System;
using BackendTechnicalAssetsManagement.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendTechnicalAssetsManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251006162847_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("17ab667c-6223-4f3e-af98-def86d4df41b"),
                            Category = "Electronics",
                            Condition = "New",
                            CreatedAt = new DateTime(2025, 10, 6, 16, 28, 46, 846, DateTimeKind.Utc).AddTicks(3910),
                            Description = "High-performance laptop for students.",
                            ItemMake = "Dell",
                            ItemModel = "XPS 15",
                            ItemName = "Laptop",
                            ItemType = "Electronic",
                            SerialNumber = "SN123456",
                            UpdatedAt = new DateTime(2025, 10, 6, 16, 28, 46, 846, DateTimeKind.Utc).AddTicks(3911)
                        },
                        new
                        {
                            Id = new Guid("44f49436-802a-4123-a7e3-56a6d6698f51"),
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 6, 16, 28, 46, 846, DateTimeKind.Utc).AddTicks(3916),
                            Description = "Portable projector for classroom use.",
                            ItemMake = "Epson",
                            ItemModel = "PowerLite 1781W",
                            ItemName = "Projector",
                            ItemType = "Electronic",
                            SerialNumber = "SN654321",
                            UpdatedAt = new DateTime(2025, 10, 6, 16, 28, 46, 846, DateTimeKind.Utc).AddTicks(3916)
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("LentItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4246f7b7-9fc4-42c2-a76c-0149d66cee13"),
                            BorrowerFullName = "Peter Jones",
                            BorrowerRole = "Student",
                            ItemId = new Guid("17ab667c-6223-4f3e-af98-def86d4df41b"),
                            LentAt = new DateTime(2025, 10, 6, 16, 28, 46, 846, DateTimeKind.Utc).AddTicks(3997),
                            Remarks = "Borrowed",
                            Room = "Room 101",
                            StudentIdNumber = "2023-0001",
                            SubjectTimeSchedule = "MWF 10:00-11:00 AM",
                            TeacherFullName = "Mary Williams",
                            TeacherId = new Guid("d569775c-6b95-40c4-be66-15cfdebbf9c9"),
                            UserId = new Guid("346f47a0-beb7-4582-9d4e-9132795ea136")
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Admin", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Admins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1801f88e-918f-40f3-bf4e-4ac76484c45c"),
                            Email = "superadmin@example.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEIDZpIPp5QDoSU8KhzHfi05O70LaVthMRcBpDDQs/xR1IC4ZmBn59cMLHt/kqoDGBA==",
                            Status = "Active",
                            UserRole = "SuperAdmin",
                            Username = "superadmin",
                            PhoneNumber = "999-999-9999"
                        },
                        new
                        {
                            Id = new Guid("deb6d5e4-9c80-4d8c-a0ab-038a6183c983"),
                            Email = "admin@gmail.com",
                            FirstName = "admin",
                            LastName = "admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEJzXqsq8R3h5N6bH3hKgaGG2wB0bGZcNcZC4lG5/4lWzuHKY1biVz+cNOw1rL48CqQ==",
                            Status = "Active",
                            UserRole = "Admin",
                            Username = "admin",
                            PhoneNumber = "123-456-7890"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4594b00d-9a8a-497f-8193-132def803275"),
                            Email = "staff@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "AQAAAAIAAYagAAAAELZHgzdFAxWmjzPRhWRweyULh9rQTT3vWlNSAMwPn0ZESCVBS0QarTJjKY140sRFAA==",
                            Status = "Active",
                            UserRole = "Staff",
                            Username = "staff",
                            PhoneNumber = "098-765-4321",
                            Position = "Lab Technician"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("346f47a0-beb7-4582-9d4e-9132795ea136"),
                            Email = "student@example.com",
                            FirstName = "Peter",
                            LastName = "Jones",
                            PasswordHash = "AQAAAAIAAYagAAAAEL8ABoVGUq3eaqfKm320Gcdg/9JVoMp5i8cCPL4O5y1rCPR9w27NLcdFdVvJPo59mQ==",
                            Status = "Active",
                            UserRole = "Student",
                            Username = "student",
                            CityMunicipality = "Anytown",
                            Course = "Computer Science",
                            PhoneNumber = "555-123-4567",
                            PostalCode = "12345",
                            Province = "Anyprovince",
                            Section = "A",
                            Street = "123 Main St",
                            StudentIdNumber = "2023-0001",
                            Year = "3"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d569775c-6b95-40c4-be66-15cfdebbf9c9"),
                            Email = "teacher@example.com",
                            FirstName = "Mary",
                            LastName = "Williams",
                            PasswordHash = "AQAAAAIAAYagAAAAEFDaeC+8/CUAwZoMoKKe0I/bH+M048clO4El8Noo0J3/hXWFCdXIS0cOhtTCBr6b5Q==",
                            Status = "Active",
                            UserRole = "Teacher",
                            Username = "teacher",
                            Department = "Information Technology",
                            PhoneNumber = "555-987-6543"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Admin", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Staff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
