// <auto-generated />
using System;
using BackendTechnicalAssetsManagement.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendTechnicalAssetsManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251031050156_UpdateLentItemsBarcodeFormat")]
    partial class UpdateLentItemsBarcodeFormat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ArchiveItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("ArchiveLentItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OriginalUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserRole")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArchiveUsers");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5cb4780d-812c-48cf-aa78-a03fd3a6a47c"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 31, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(6910),
                            Description = "High-performance laptop for video editing.",
                            ItemMake = "Dell",
                            ItemModel = "XPS 15 9510",
                            ItemName = "Dell XPS 15 Laptop",
                            ItemType = "Laptop",
                            SerialNumber = "SN-LP-DELL-001",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 31, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(6911)
                        },
                        new
                        {
                            Id = new Guid("1808a478-ee4c-41d4-bcd9-442969c5f037"),
                            Category = "MediaEquipment",
                            Condition = "New",
                            CreatedAt = new DateTime(2025, 10, 31, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(6917),
                            Description = "1080p projector for classroom presentations.",
                            ItemMake = "Epson",
                            ItemModel = "HC 2250",
                            ItemName = "Epson Home Cinema Projector",
                            ItemType = "Projector",
                            SerialNumber = "SN-PR-EPS-002",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 31, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(6918)
                        },
                        new
                        {
                            Id = new Guid("b45c779f-4099-457d-9604-3e4cc6969948"),
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 31, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(6922),
                            Description = "Full-frame mirrorless camera with 4K video.",
                            ItemMake = "Canon",
                            ItemModel = "EOS R6",
                            ItemName = "Canon EOS R6 Camera",
                            ItemType = "Camera",
                            SerialNumber = "SN-CM-CAN-003",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 31, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(6922)
                        },
                        new
                        {
                            Id = new Guid("98007650-218a-4baf-b731-8cdbc76d6651"),
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 31, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(6926),
                            Description = "Dynamic microphone for vocal recording.",
                            ItemMake = "Shure",
                            ItemModel = "SM7B",
                            ItemName = "Shure SM7B Microphone",
                            ItemType = "Microphone",
                            SerialNumber = "SN-MC-SHR-004",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 31, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(6929)
                        },
                        new
                        {
                            Id = new Guid("abffe3b6-04fa-489c-ac3e-e9ae39b853b0"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 31, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(6933),
                            Description = "Tablet for digital art and design classes.",
                            ItemMake = "Apple",
                            ItemModel = "iPad Pro 12.9-inch",
                            ItemName = "Apple iPad Pro",
                            ItemType = "Tablet",
                            SerialNumber = "SN-TB-APL-005",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 31, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(6934)
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("LentItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16096275-55ce-4b63-9df7-b117234a53e2"),
                            BorrowerFullName = "John Doe",
                            BorrowerRole = "Student",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("5cb4780d-812c-48cf-aa78-a03fd3a6a47c"),
                            ItemName = "Dell XPS 15 Laptop",
                            LentAt = new DateTime(2025, 10, 26, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(7624),
                            Room = "",
                            Status = "Borrowed",
                            StudentIdNumber = "S2021-001",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "Alice Williams",
                            TeacherId = new Guid("b6d116ae-df63-4284-a0aa-2b1fc46b31ae"),
                            UserId = new Guid("70667c61-1f72-431c-a9be-c2208295fefb")
                        },
                        new
                        {
                            Id = new Guid("b184cf02-4ec0-4aba-9b14-184620f2044a"),
                            BorrowerFullName = "Jane Smith",
                            BorrowerRole = "Student",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("b45c779f-4099-457d-9604-3e4cc6969948"),
                            ItemName = "Canon EOS R6 Camera",
                            LentAt = new DateTime(2025, 10, 21, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(7643),
                            ReturnedAt = new DateTime(2025, 10, 29, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(7644),
                            Room = "",
                            Status = "Returned",
                            StudentIdNumber = "S2021-002",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "Bob Brown",
                            TeacherId = new Guid("a3d80db9-70ba-4069-b505-5e6cc5358b5b"),
                            UserId = new Guid("a402a76b-3b93-4b2d-a075-1ccbf3da568d")
                        },
                        new
                        {
                            Id = new Guid("42554f4d-a6b9-4fb1-be12-4e37b7c54a5c"),
                            BorrowerFullName = "Peter Jones",
                            BorrowerRole = "Student",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("1808a478-ee4c-41d4-bcd9-442969c5f037"),
                            ItemName = "Epson Home Cinema Projector",
                            LentAt = new DateTime(2025, 10, 30, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(7651),
                            Room = "",
                            Status = "Borrowed",
                            StudentIdNumber = "S2021-003",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "Alice Williams",
                            TeacherId = new Guid("b6d116ae-df63-4284-a0aa-2b1fc46b31ae"),
                            UserId = new Guid("89f1142c-4425-4c99-a592-720a0bf785c5")
                        },
                        new
                        {
                            Id = new Guid("a604b8e2-26aa-45ee-b586-2e72172edee6"),
                            BorrowerFullName = "Alice Williams",
                            BorrowerRole = "Teacher",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("98007650-218a-4baf-b731-8cdbc76d6651"),
                            ItemName = "Shure SM7B Microphone",
                            LentAt = new DateTime(2025, 10, 28, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(7654),
                            Room = "",
                            Status = "Borrowed",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "",
                            UserId = new Guid("b6d116ae-df63-4284-a0aa-2b1fc46b31ae")
                        },
                        new
                        {
                            Id = new Guid("233e8791-588f-4645-9e2d-22d0b5a7bfdc"),
                            BorrowerFullName = "Bob Brown",
                            BorrowerRole = "Teacher",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("abffe3b6-04fa-489c-ac3e-e9ae39b853b0"),
                            ItemName = "Apple iPad Pro",
                            LentAt = new DateTime(2025, 10, 1, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(7660),
                            ReturnedAt = new DateTime(2025, 10, 16, 5, 1, 55, 555, DateTimeKind.Utc).AddTicks(7660),
                            Room = "",
                            Status = "Returned",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "",
                            UserId = new Guid("a3d80db9-70ba-4069-b505-5e6cc5358b5b")
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1798bec-b230-4e6c-88d9-55daaa72e564"),
                            Email = "superadmin@example.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "$2a$11$VR.RbIeqEi38HaH6gAOaWOEuvZpoKPtui9MCBXJT1F7UcAyzt5KWi",
                            Status = "Offline",
                            UserRole = "SuperAdmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = new Guid("3d16bf60-b629-492e-8e43-9b80339d05e0"),
                            Email = "admin1@example.com",
                            FirstName = "Admin1",
                            LastName = "User",
                            PasswordHash = "$2a$11$h.ywu2763xUk9AGlzFh.1eIcMhZQHgODo9UgMLtQLNfD9FoTPO9o6",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = new Guid("e46888af-9474-472d-b15c-b7a1a83b0da1"),
                            Email = "admin2@example.com",
                            FirstName = "Admin2",
                            LastName = "User",
                            PasswordHash = "$2a$11$a.LLTihJ4peZnknMmYXusOoUIekMqud0p9DjN/B35wVTbnntDSyRq",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = new Guid("3bfb3538-d973-4edb-ae64-a82672f3ae0e"),
                            Email = "admin3@example.com",
                            FirstName = "Admin3",
                            LastName = "User",
                            PasswordHash = "$2a$11$gKBOilsIkkh.WyPilmAsCuc1NgCZFiah/Xl.Q850hpx3mK6M4Bg/y",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin3"
                        },
                        new
                        {
                            Id = new Guid("76a4a5d3-1913-4733-bf32-eeef7ac38d15"),
                            Email = "admin4@example.com",
                            FirstName = "Admin4",
                            LastName = "User",
                            PasswordHash = "$2a$11$F6l.6Uq1s2nH6yaf2Ht6lOSIoHdkI4X39W0amsOqKLuanJPzqEcdG",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin4"
                        },
                        new
                        {
                            Id = new Guid("b8ca4420-e8f5-40c2-a3c2-b24c34d76e76"),
                            Email = "admin5@example.com",
                            FirstName = "Admin5",
                            LastName = "User",
                            PasswordHash = "$2a$11$wbtX/lWZ5tezn1.xeyw8PeNkCxl.3QcuOl5T9AV0L3ORiYXoyxy.y",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin5"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveStaff", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CityMunicipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveStudents", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveTeachers", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("13bec163-b287-4e70-b68c-4b1c2e07fb30"),
                            Email = "staff1@example.com",
                            FirstName = "Staff1",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$.xK4Gw6v8Q7zlpDOEiydz.Wig05y4Pu2FW6uoKWMGNB4aYdLm2.Uy",
                            PhoneNumber = "0998176543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff1",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("dec461b7-7687-46ae-a1f6-5ffa64f501af"),
                            Email = "staff2@example.com",
                            FirstName = "Staff2",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$XmLjJMmuEzws.YEZ7SxvOuM54RquBAPdcG9zxg4ZtbnAL5LE.Ne3i",
                            PhoneNumber = "0998276543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff2",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("5ac6a324-25fc-468b-9988-b9acd07c7982"),
                            Email = "staff3@example.com",
                            FirstName = "Staff3",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$T1Vi.nJrTa8JDB8PNs2X2uPoyB1VhwuRe8iosrI0sPgGBqoeoPk3q",
                            PhoneNumber = "0998376543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff3",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("75e86d5e-10e4-4211-871d-06ef2266e3a9"),
                            Email = "staff4@example.com",
                            FirstName = "Staff4",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$LlgXuG0w7xQu1cziWFyuWe6qkdARtXdw/G.nkKF/.X6KOUkrw9PIC",
                            PhoneNumber = "0998476543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff4",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("67230c4b-d9f2-4be5-a9a3-92d5fab82a56"),
                            Email = "staff5@example.com",
                            FirstName = "Staff5",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$hBQo9cOPUofHe2uC9RSxle9BQGZV6jOfzsQUJCU4WDDxVroedwFM6",
                            PhoneNumber = "0998576543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff5",
                            Position = "Lab Technician"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("StudentIdNumber")
                        .IsUnique()
                        .HasFilter("([StudentIdNumber] IS NOT NULL AND [StudentIdNumber] <> '')");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("70667c61-1f72-431c-a9be-c2208295fefb"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$rH68BeMGWzWscHciQgPLsOyMvkLJC6rv/0mPkBCRpnWTZJ/abf962",
                            PhoneNumber = "0912134567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "johndoe",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "S2021-001",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("a402a76b-3b93-4b2d-a075-1ccbf3da568d"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$q9FSylUo0aBSTnNffCJQxOeDvaFJC1A.dO8/CFOaymN6Nqy7dFWv6",
                            PhoneNumber = "0912234567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "janesmith",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "S2021-002",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("89f1142c-4425-4c99-a592-720a0bf785c5"),
                            Email = "peter.jones@example.com",
                            FirstName = "Peter",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$lCF7yEGZhPDRVmR.JU/QAummwIKdbZkmaqe.PhZzeUwXgKofI4Gb6",
                            PhoneNumber = "0912334567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "peterjones",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "S2021-003",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("1106d7a8-eb7b-42cf-8b64-74286fea84ba"),
                            Email = "student4@example.com",
                            FirstName = "Student4",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$xHjtm.9F7spPUvLqH8fG5.U2nQuCQnnJCsTkZ6V1Z/xuECX7HCwYG",
                            PhoneNumber = "0912434567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student4",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "2023-0004",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("1e9106d3-73ec-4438-b08a-000eec5798f6"),
                            Email = "student5@example.com",
                            FirstName = "Student5",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$ey7RBAFcIiLMpTElBVXVZuKFQh09fIQpcalv2cWiCRPQeHLUJAxMS",
                            PhoneNumber = "0912534567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student5",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "2023-0005",
                            Year = "3"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6d116ae-df63-4284-a0aa-2b1fc46b31ae"),
                            Email = "alice.williams@example.com",
                            FirstName = "Alice",
                            LastName = "Williams",
                            PasswordHash = "$2a$11$8PbcupGKpj8slWqJZcLDwuuyojztt9EhfqPzpm5GLJg8OrRIimyWO",
                            PhoneNumber = "0917123456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "alicewilliams",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("a3d80db9-70ba-4069-b505-5e6cc5358b5b"),
                            Email = "bob.brown@example.com",
                            FirstName = "Bob",
                            LastName = "Brown",
                            PasswordHash = "$2a$11$05gXL3kf7Kpj/Adr4i1/aOfo9Y1sgxgA5N.As2Ank2G0zvJOZUrhS",
                            PhoneNumber = "0917223456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "bobbrown",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("a45b3918-3621-4a3c-b6b3-9e05849d3c73"),
                            Email = "teacher3@example.com",
                            FirstName = "Teacher3",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$U.nZGY/nVZze6qCOolHeAe7aH10NSIB1jsMkMdhI/mWalw4KVCzZK",
                            PhoneNumber = "0917323456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher3",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("d2db5d22-8988-4b7c-b9e7-d130d0e0886f"),
                            Email = "teacher4@example.com",
                            FirstName = "Teacher4",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$kkRAYtAaVDX6El6qVK29euXNprNR.UfrLqx0LDZeImqUkkdhPqcci",
                            PhoneNumber = "0917423456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher4",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("8159e8a2-f024-403d-8dd0-d23e8c4ce083"),
                            Email = "teacher5@example.com",
                            FirstName = "Teacher5",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$qkE.isCVU5kGvBckv.bPm.2BZvIcoBmIfBl/hOsBVLWZVLpN8OHqu",
                            PhoneNumber = "0917523456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher5",
                            Department = "Information Technology"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("LentItems")
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Staff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Navigation("LentItems");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
