// <auto-generated />
using System;
using BackendTechnicalAssetsManagement.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendTechnicalAssetsManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251018033221_AddedUserArchiveEntity")]
    partial class AddedUserArchiveEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ArchiveItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LentItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("ArchiveLentItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OriginalUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserRole")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArchiveUsers");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("LentItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("7606e4ad-efd5-4130-bff3-19d2da86e342"),
                            Email = "superadmin@example.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "$2a$11$Q292p9ufaIp0MhaiXlWIquMrdizEapgcVPS/RZ1Qn2QVeLz7DESKW",
                            Status = "Offline",
                            UserRole = "SuperAdmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = new Guid("451289ca-c259-4a0b-b269-d16fbf6aef95"),
                            Email = "admin1@example.com",
                            FirstName = "Admin1",
                            LastName = "User",
                            PasswordHash = "$2a$11$JkPfiyyrfazD5JXPdy7w3.WS304BpYF9o4fvhiC6gdNeQfuGLe9mu",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = new Guid("f45d63b8-e00d-4624-a48d-4e8020770140"),
                            Email = "admin2@example.com",
                            FirstName = "Admin2",
                            LastName = "User",
                            PasswordHash = "$2a$11$RLW.vehAGfShXkgw9RlQQeSLUakbn4OtL098v8hddPmuBfSNefvge",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = new Guid("8e40d83d-5291-4f7d-bb48-57ce6f533443"),
                            Email = "admin3@example.com",
                            FirstName = "Admin3",
                            LastName = "User",
                            PasswordHash = "$2a$11$gKUu8tqB60fzUWIdT5zDIuoBRfyL75IUVFrRcYIIQ5XEhKlOZoV5e",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin3"
                        },
                        new
                        {
                            Id = new Guid("9002f1ce-34d8-4a96-8588-8df7777b7802"),
                            Email = "admin4@example.com",
                            FirstName = "Admin4",
                            LastName = "User",
                            PasswordHash = "$2a$11$bpRnlwUZ7h3kGT0yRLhZ1.UhOYJrALHNcXSt1mgxDJ8r.i06LsnJW",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin4"
                        },
                        new
                        {
                            Id = new Guid("0366d205-1632-41d3-8fda-1214f9d09675"),
                            Email = "admin5@example.com",
                            FirstName = "Admin5",
                            LastName = "User",
                            PasswordHash = "$2a$11$Tb0GNbfbCYzFSRjQyNxQhekhxygUmYxcN8QPUQhgG7n.q.TEy7NE.",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin5"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveStaff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveUser");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveStaff", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveStudent", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveUser");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CityMunicipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveStudents", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveTeacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveUser");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveTeachers", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("029a8a52-5c48-45d7-924a-c95e9bbd6fa8"),
                            Email = "staff1@example.com",
                            FirstName = "Staff1",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$EN8piMXz2mEgURlDVN57weX7nweN7lpY4St3Gsul9aLJigddRIQ06",
                            PhoneNumber = "0998176543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff1",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("69e5c682-1836-4d67-85a7-8252f02b44e2"),
                            Email = "staff2@example.com",
                            FirstName = "Staff2",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$hhB4BLghR0Pb8Vqn243wu.Bi.sxQEV8lKpHgQ5n.DW1NipC2k9qo6",
                            PhoneNumber = "0998276543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff2",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("915c6b5b-920f-4fae-a5d9-faca2b03bdb4"),
                            Email = "staff3@example.com",
                            FirstName = "Staff3",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$wgoRrsp9U0DyFfY/r0uJGe0q16.ZQp42XUtxxEM9guf9aTBsT.ZH2",
                            PhoneNumber = "0998376543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff3",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("a9c6c964-bc81-40a3-bb23-e835f7a97b96"),
                            Email = "staff4@example.com",
                            FirstName = "Staff4",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$J.igY4DcMvMq7zpd/prk0OLMjHTTSRwr0PpkWRapCwu/OpeYOkBji",
                            PhoneNumber = "0998476543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff4",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("912035aa-7e50-45dd-a44b-e248f74f9073"),
                            Email = "staff5@example.com",
                            FirstName = "Staff5",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$If24Oo444EjPNfZkmmfaj.7Jr1krtdybEJmxEEsDluVUsDrqyw.k6",
                            PhoneNumber = "0998576543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff5",
                            Position = "Lab Technician"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("StudentIdNumber")
                        .IsUnique()
                        .HasFilter("([StudentIdNumber] IS NOT NULL AND [StudentIdNumber] <> '')");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9424ba2f-744c-4e74-9e44-a82cf2492257"),
                            Email = "student1@example.com",
                            FirstName = "Student1",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$O1RPoQSefwMscLIBoE6rWuBSBpE.lc0Dq4kCXVI16i5dUgSAvB0tG",
                            PhoneNumber = "0912134567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student1",
                            CityMunicipality = "Sample City",
                            Course = "Computer Science",
                            PostalCode = "12345",
                            Province = "Sample Province",
                            Section = "A",
                            Street = "123 Main St #1",
                            StudentIdNumber = "2023-0001",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("7ce13a83-09f6-402a-9f1b-ab34ab2c1cbe"),
                            Email = "student2@example.com",
                            FirstName = "Student2",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$fvzsWP318QhbIoupxIr0mefeF3pvKd62CV7NzWCL3z49vvCb0NM3a",
                            PhoneNumber = "0912234567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student2",
                            CityMunicipality = "Sample City",
                            Course = "Computer Science",
                            PostalCode = "12345",
                            Province = "Sample Province",
                            Section = "A",
                            Street = "123 Main St #2",
                            StudentIdNumber = "2023-0002",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("0e25db68-5a92-4b44-8d13-bc486d834e36"),
                            Email = "student3@example.com",
                            FirstName = "Student3",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$CKIzG.prPmMqP48oetKEz.twKbcSMHBHlefR4x26.nMRbflE7fjQO",
                            PhoneNumber = "0912334567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student3",
                            CityMunicipality = "Sample City",
                            Course = "Computer Science",
                            PostalCode = "12345",
                            Province = "Sample Province",
                            Section = "A",
                            Street = "123 Main St #3",
                            StudentIdNumber = "2023-0003",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("25207d58-9584-4509-9315-0edc55767d26"),
                            Email = "student4@example.com",
                            FirstName = "Student4",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$4NSZE4Kk69aCqHg107LGweISDTqd62QYpYdBywHdYbJuXNGn3XT/y",
                            PhoneNumber = "0912434567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student4",
                            CityMunicipality = "Sample City",
                            Course = "Computer Science",
                            PostalCode = "12345",
                            Province = "Sample Province",
                            Section = "A",
                            Street = "123 Main St #4",
                            StudentIdNumber = "2023-0004",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("62625b62-bbce-4215-8e7d-f0c3e3e7be12"),
                            Email = "student5@example.com",
                            FirstName = "Student5",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$k9vzmb8dyuS7XzNpwDm/AezaMeqXkqTYqVx0m4DdQF7R579/9rfKO",
                            PhoneNumber = "0912534567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student5",
                            CityMunicipality = "Sample City",
                            Course = "Computer Science",
                            PostalCode = "12345",
                            Province = "Sample Province",
                            Section = "A",
                            Street = "123 Main St #5",
                            StudentIdNumber = "2023-0005",
                            Year = "3"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bcbb79eb-1ec3-4789-aac8-21fc370060b7"),
                            Email = "teacher1@example.com",
                            FirstName = "Teacher1",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$5EYV.Cf4MpeUOUL37yG90OswUtxvSQ2dGZJgNSbPXy6B7mppHWOKC",
                            PhoneNumber = "0917123456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher1",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("774b27ab-3283-4c1f-a613-4db341da56f1"),
                            Email = "teacher2@example.com",
                            FirstName = "Teacher2",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$qHN0Ll/CykxXyqjODCvAaOYM59XLD49w4ZMAd8aZkdP8/d4BRIjwG",
                            PhoneNumber = "0917223456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher2",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("ee79979c-9068-49e5-a486-dffdfee6a094"),
                            Email = "teacher3@example.com",
                            FirstName = "Teacher3",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$KO.wIxoOEtv2mkaJSMsXRu3sYrX/3zzypWfBUo6dHamLn/iOkJAWS",
                            PhoneNumber = "0917323456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher3",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("d27a04a2-af24-4366-bb49-6ff428f16c8a"),
                            Email = "teacher4@example.com",
                            FirstName = "Teacher4",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$T4BsA6EsdVizVBOf7Uc/zexpSLMXRA/EqZU/pjYwDVhgCozETPOti",
                            PhoneNumber = "0917423456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher4",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("01d8c593-93d2-4c41-b452-aefad0b7e580"),
                            Email = "teacher5@example.com",
                            FirstName = "Teacher5",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$PCmiYBYBmVmTrPgXovt4XuAu8NLOJASXPPrJ0t.edqFarOlelh5j2",
                            PhoneNumber = "0917523456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher5",
                            Department = "Information Technology"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("LentItems")
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveStaff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveStaff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveStudent", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveStudent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveTeacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveUsers.ArchiveTeacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Staff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Navigation("LentItems");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
