// <auto-generated />
using System;
using BackendTechnicalAssetsManagement.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendTechnicalAssetsManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251016130537_AddUserRoleSeeds")]
    partial class AddUserRoleSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ArchiveItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LentItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("ArchiveLentItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("LentItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("c86e8899-dd93-4af4-805b-c15676f0b1ca"),
                            Email = "superadmin@example.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEJhthNcN8l/2xQI1VZZDApn5y96PyKaTi8ZZtzQHxuBRwtn/Bw5iribGYbPU0vWGBw==",
                            Status = "Offline",
                            UserRole = "SuperAdmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = new Guid("9b8e7cb2-dace-4bb0-91c2-2fcb539bf40c"),
                            Email = "admin1@example.com",
                            FirstName = "Admin1",
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEDKsTlotsJUi7SPau78m89HX25DB7aa3aNk9EvPor0TlMSvEI7lP/OCvrwpuy/IEaA==",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = new Guid("386af524-dae4-4c56-a87f-d8069bde52bf"),
                            Email = "admin2@example.com",
                            FirstName = "Admin2",
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEDPz2bA10swqRu4EM6ICQe5Rx2rkF5ZRYXkr2lhVddfGI5h8WRIFGKR8db93XdxIXg==",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = new Guid("1b759e23-ade6-417a-b253-175a4f0f8ae6"),
                            Email = "admin3@example.com",
                            FirstName = "Admin3",
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEA/Ntn+PAGAtFKRJIj6VGG8XL/6sDJrflRYvB2wPRjCp9wquQw7MuLeoDFS029fPBQ==",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin3"
                        },
                        new
                        {
                            Id = new Guid("988c222d-6c56-443f-bdf9-927cf443a2fa"),
                            Email = "admin4@example.com",
                            FirstName = "Admin4",
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEEinYoyo5ljI5CHVyEFr6FFHbDBcPIpFF49LZWvSjwwhagnJTL5zVfa0Dsxf+cz9Rg==",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin4"
                        },
                        new
                        {
                            Id = new Guid("4a36aec4-7b85-4c6f-a243-40433f8ce0f7"),
                            Email = "admin5@example.com",
                            FirstName = "Admin5",
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEN49yxefeXE901kZzPm++hy3wIiETf16fS+2n/b6pj4qx6/aNf6Ko0O7phN6aY0eLQ==",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin5"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("47112c52-d7b0-4724-865c-3507b9b06b1f"),
                            Email = "staff1@example.com",
                            FirstName = "Staff1",
                            LastName = "Doe",
                            PasswordHash = "AQAAAAIAAYagAAAAEAqGHT4+NxkVPKSbYrCUvtanm/2/t02SEdPb/sReqVg2svMyDIOTo6W4UShzJ+cwcQ==",
                            PhoneNumber = "0998176543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff1",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("e387f4da-284c-4756-9469-357772cd67ea"),
                            Email = "staff2@example.com",
                            FirstName = "Staff2",
                            LastName = "Doe",
                            PasswordHash = "AQAAAAIAAYagAAAAEOsGfBBuu6D+X2Ozruvms8Zu717mTQMtAJqqstc8LvcyQZISW3NbyNvHIZwx7MXKcA==",
                            PhoneNumber = "0998276543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff2",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("17dd384c-e54f-4981-acca-025d93b36560"),
                            Email = "staff3@example.com",
                            FirstName = "Staff3",
                            LastName = "Doe",
                            PasswordHash = "AQAAAAIAAYagAAAAEI613a2m2wC5xay2mryiNN2TaXX/SYDt59DGmkP6wLwcFLNBT86XmdXXku0pG68oyA==",
                            PhoneNumber = "0998376543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff3",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("d72165ec-a7f7-4925-9063-15a15f7db606"),
                            Email = "staff4@example.com",
                            FirstName = "Staff4",
                            LastName = "Doe",
                            PasswordHash = "AQAAAAIAAYagAAAAEEn7+152TmNPrwIgN7YxNPhHXuL1OoL7AOWPUFWFy0bDayV/MVQCvdWqAuHoOLRbMQ==",
                            PhoneNumber = "0998476543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff4",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("4b1d35b2-75b0-4e59-b67d-49dfb8061053"),
                            Email = "staff5@example.com",
                            FirstName = "Staff5",
                            LastName = "Doe",
                            PasswordHash = "AQAAAAIAAYagAAAAEBatC5xXtet4DMmSKDquf56dJh+ZwwVAjd/j1XJ0mMKulZBT7tuwvQaP7OXedrOmbA==",
                            PhoneNumber = "0998576543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff5",
                            Position = "Lab Technician"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("StudentIdNumber")
                        .IsUnique()
                        .HasFilter("([StudentIdNumber] IS NOT NULL AND [StudentIdNumber] <> '')");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f1e0268-a800-4800-9b4c-36fab9398ecb"),
                            Email = "student1@example.com",
                            FirstName = "Student1",
                            LastName = "Jones",
                            PasswordHash = "AQAAAAIAAYagAAAAEAQl1GYxLGI0UJuu7SkBMgm1m2PszK89YBWBiKnLZ8po6PBFC/6yuc5f4qrFw31qVQ==",
                            PhoneNumber = "0912134567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student1",
                            CityMunicipality = "Sample City",
                            Course = "Computer Science",
                            PostalCode = "12345",
                            Province = "Sample Province",
                            Section = "A",
                            Street = "123 Main St #1",
                            StudentIdNumber = "2023-0001",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("1fea876e-f3f8-4369-9623-2890b8022eb3"),
                            Email = "student2@example.com",
                            FirstName = "Student2",
                            LastName = "Jones",
                            PasswordHash = "AQAAAAIAAYagAAAAEPgMgeU1qDtnoMYm1uZgjJrqtTIu/5XlI0l2/VFeS/onTg1d6uG0d1QU6cfnmjKqMQ==",
                            PhoneNumber = "0912234567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student2",
                            CityMunicipality = "Sample City",
                            Course = "Computer Science",
                            PostalCode = "12345",
                            Province = "Sample Province",
                            Section = "A",
                            Street = "123 Main St #2",
                            StudentIdNumber = "2023-0002",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("1ed05039-5195-4847-ab11-a399bde07314"),
                            Email = "student3@example.com",
                            FirstName = "Student3",
                            LastName = "Jones",
                            PasswordHash = "AQAAAAIAAYagAAAAEE7M56prYxT2PJXnKRhN1tzVjeGSFPAtobvhXYCA+cHdxvC0jmLEkERx+ShjeeZ1og==",
                            PhoneNumber = "0912334567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student3",
                            CityMunicipality = "Sample City",
                            Course = "Computer Science",
                            PostalCode = "12345",
                            Province = "Sample Province",
                            Section = "A",
                            Street = "123 Main St #3",
                            StudentIdNumber = "2023-0003",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("6de9eb5c-0d29-41ad-ac42-e292bc2ea689"),
                            Email = "student4@example.com",
                            FirstName = "Student4",
                            LastName = "Jones",
                            PasswordHash = "AQAAAAIAAYagAAAAEKkCV1l0Jqo0haTtJhDgR/u3oQm4yFb3dOPMt8XKa84SOp/86+jONFYgG/0NbxxGHA==",
                            PhoneNumber = "0912434567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student4",
                            CityMunicipality = "Sample City",
                            Course = "Computer Science",
                            PostalCode = "12345",
                            Province = "Sample Province",
                            Section = "A",
                            Street = "123 Main St #4",
                            StudentIdNumber = "2023-0004",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("f6d7128e-8eba-400e-81fb-cfaa1d3f3e1c"),
                            Email = "student5@example.com",
                            FirstName = "Student5",
                            LastName = "Jones",
                            PasswordHash = "AQAAAAIAAYagAAAAENeV4diWFAuYKQX1pqHTVlaVSBtjferwtS1QJlBBiKO22H4jnpvLLejtkwDRTT7/Xw==",
                            PhoneNumber = "0912534567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student5",
                            CityMunicipality = "Sample City",
                            Course = "Computer Science",
                            PostalCode = "12345",
                            Province = "Sample Province",
                            Section = "A",
                            Street = "123 Main St #5",
                            StudentIdNumber = "2023-0005",
                            Year = "3"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("426b7e7d-a6ea-49a6-9248-1d9397741646"),
                            Email = "teacher1@example.com",
                            FirstName = "Teacher1",
                            LastName = "Smith",
                            PasswordHash = "AQAAAAIAAYagAAAAEPLW0K/INgF7WIGpugMMcnyKhID1YOZG2qrSl9HMI+Y+l/q8sQ7vllH91x+Jg8xQpw==",
                            PhoneNumber = "0917123456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher1",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("d2993d16-a66a-4f7e-aed5-42a4636ccf5d"),
                            Email = "teacher2@example.com",
                            FirstName = "Teacher2",
                            LastName = "Smith",
                            PasswordHash = "AQAAAAIAAYagAAAAED+teb+FvJTKvPbLt8VWva4QyJKPyGrd8QEKMcs5ddMs51JAkPqWVhcWJ+WPl6vWKQ==",
                            PhoneNumber = "0917223456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher2",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("54a28d24-0c4b-4696-93ff-196f1d922c7a"),
                            Email = "teacher3@example.com",
                            FirstName = "Teacher3",
                            LastName = "Smith",
                            PasswordHash = "AQAAAAIAAYagAAAAEKmc2QPxO4PXCIY/qWitv6NLqUNpWBpbM5084WRFORZot3qAC4WOOCVPITNlFRq3fw==",
                            PhoneNumber = "0917323456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher3",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("fdfbb9e1-307e-4528-8124-a2e2cc747cb4"),
                            Email = "teacher4@example.com",
                            FirstName = "Teacher4",
                            LastName = "Smith",
                            PasswordHash = "AQAAAAIAAYagAAAAEL14QpjXKxBGPjMOgC0kXD+bhe5U4SnyJe66LL13zsb3E0d7ZRdH6sgOXlC/6/Slnw==",
                            PhoneNumber = "0917423456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher4",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("458fc8b1-8f35-4bd8-bfca-c8e3e1f07e22"),
                            Email = "teacher5@example.com",
                            FirstName = "Teacher5",
                            LastName = "Smith",
                            PasswordHash = "AQAAAAIAAYagAAAAEHH4FBFgJjNYT+rHKHQKBECi9eCFbvZgBYVPSt8QZLHW1NANdtEU/jFMRuspaY0K2Q==",
                            PhoneNumber = "0917523456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher5",
                            Department = "Information Technology"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("LentItems")
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Staff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Navigation("LentItems");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
