// <auto-generated />
using System;
using BackendTechnicalAssetsManagement.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendTechnicalAssetsManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116111025_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ArchiveItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("ArchiveLentItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OriginalUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserRole")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArchiveUsers");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66ebfa17-1c85-4dc2-9df4-a1651d4d517b"),
                            Barcode = "ITEM-SN-HDMI-001",
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            Description = "10-foot HDMI cable for display connections.",
                            ItemMake = "Belkin",
                            ItemModel = "HDMI 2.0",
                            ItemName = "HDMI Cable 10ft",
                            ItemType = "Cable",
                            SerialNumber = "SN-HDMI-001",
                            Status = "Unavailable",
                            UpdatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247)
                        },
                        new
                        {
                            Id = new Guid("82ec5f2b-b7cd-4a39-a6a1-f733396afd4a"),
                            Barcode = "ITEM-SN-MIC-002",
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            Description = "Wireless microphone for presentations.",
                            ItemMake = "Shure",
                            ItemModel = "WM-200",
                            ItemName = "Wireless Microphone",
                            ItemType = "Microphone",
                            SerialNumber = "SN-MIC-002",
                            Status = "Unavailable",
                            UpdatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247)
                        },
                        new
                        {
                            Id = new Guid("50891c08-7605-4b4b-889e-7fd014a8f9c4"),
                            Barcode = "ITEM-SN-SPK-003",
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            Description = "Portable speaker for classroom audio.",
                            ItemMake = "JBL",
                            ItemModel = "Flip 6",
                            ItemName = "Portable Bluetooth Speaker",
                            ItemType = "Speaker",
                            SerialNumber = "SN-SPK-003",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247)
                        },
                        new
                        {
                            Id = new Guid("9e6ee2b3-f65b-4eed-99d8-9487f4855a0f"),
                            Barcode = "ITEM-SN-MOUSE-004",
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            Description = "Ergonomic wireless mouse.",
                            ItemMake = "Logitech",
                            ItemModel = "MX Master 3",
                            ItemName = "Wireless Mouse",
                            ItemType = "Mouse",
                            SerialNumber = "SN-MOUSE-004",
                            Status = "Unavailable",
                            UpdatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247)
                        },
                        new
                        {
                            Id = new Guid("b980bd3a-a23e-4e07-aa01-1da198d14f8d"),
                            Barcode = "ITEM-SN-KB-005",
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            Description = "Compact mechanical keyboard.",
                            ItemMake = "Logitech",
                            ItemModel = "K380",
                            ItemName = "Mechanical Keyboard",
                            ItemType = "Keyboard",
                            SerialNumber = "SN-KB-005",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247)
                        },
                        new
                        {
                            Id = new Guid("433d4153-802a-4889-a936-cc40152cf428"),
                            Barcode = "ITEM-SN-EXT-006",
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            Description = "15-foot extension cord with surge protection.",
                            ItemMake = "Belkin",
                            ItemModel = "Heavy Duty",
                            ItemName = "Extension Wire 15ft",
                            ItemType = "Extension Wire",
                            SerialNumber = "SN-EXT-006",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247)
                        },
                        new
                        {
                            Id = new Guid("5b027da2-8573-4da9-88ab-645fc5f1b71a"),
                            Barcode = "ITEM-SN-HDMI-007",
                            Category = "Electronics",
                            Condition = "New",
                            CreatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            Description = "6-foot HDMI cable for short connections.",
                            ItemMake = "AmazonBasics",
                            ItemModel = "HDMI 2.1",
                            ItemName = "HDMI Cable 6ft",
                            ItemType = "Cable",
                            SerialNumber = "SN-HDMI-007",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247)
                        },
                        new
                        {
                            Id = new Guid("6a9fa638-3a30-4a3e-b6d6-5d7a462e7256"),
                            Barcode = "ITEM-SN-MIC-008",
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            Description = "USB condenser microphone for recording.",
                            ItemMake = "Blue",
                            ItemModel = "Yeti",
                            ItemName = "USB Microphone",
                            ItemType = "Microphone",
                            SerialNumber = "SN-MIC-008",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 11, 16, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247)
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("LentItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("444b95cf-0bc1-44ba-9079-1f0a5a6ee2e1"),
                            Barcode = "LENT-20251111-001",
                            BorrowerFullName = "John Doe",
                            BorrowerRole = "Student",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("66ebfa17-1c85-4dc2-9df4-a1651d4d517b"),
                            ItemName = "HDMI Cable 10ft",
                            LentAt = new DateTime(2025, 11, 11, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            Room = "Room 301",
                            Status = "Borrowed",
                            StudentIdNumber = "S2021-001",
                            SubjectTimeSchedule = "CS101 - MWF 9:00-10:30 AM",
                            TeacherFullName = "Alice Williams",
                            TeacherId = new Guid("4138386d-26ff-478a-b036-5d5fa6b59847"),
                            UserId = new Guid("2535298c-1b8c-4039-9b4e-17cf84b36249")
                        },
                        new
                        {
                            Id = new Guid("afb07ab7-9d2c-4526-ae07-72d3f363ba8d"),
                            Barcode = "LENT-20251106-001",
                            BorrowerFullName = "Jane Smith",
                            BorrowerRole = "Student",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("50891c08-7605-4b4b-889e-7fd014a8f9c4"),
                            ItemName = "Portable Bluetooth Speaker",
                            LentAt = new DateTime(2025, 11, 6, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            ReturnedAt = new DateTime(2025, 11, 14, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            Room = "Room 205",
                            Status = "Returned",
                            StudentIdNumber = "S2021-002",
                            SubjectTimeSchedule = "MEDIA101 - TTH 1:00-2:30 PM",
                            TeacherFullName = "Bob Brown",
                            TeacherId = new Guid("8e270c16-b686-46c6-811e-a1729e834625"),
                            UserId = new Guid("14bb9ebd-6e42-40c8-bde4-f5f63a80e3b8")
                        },
                        new
                        {
                            Id = new Guid("0d921574-5c39-4156-8c11-8029174ca96c"),
                            Barcode = "LENT-20251115-001",
                            BorrowerFullName = "Peter Jones",
                            BorrowerRole = "Student",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("82ec5f2b-b7cd-4a39-a6a1-f733396afd4a"),
                            ItemName = "Wireless Microphone",
                            LentAt = new DateTime(2025, 11, 15, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            Room = "Room 401",
                            Status = "Borrowed",
                            StudentIdNumber = "S2021-003",
                            SubjectTimeSchedule = "CS201 - MWF 2:00-3:30 PM",
                            TeacherFullName = "Alice Williams",
                            TeacherId = new Guid("4138386d-26ff-478a-b036-5d5fa6b59847"),
                            UserId = new Guid("22716e25-502a-47c5-bd3a-8563abcd7fb1")
                        },
                        new
                        {
                            Id = new Guid("be57c8f6-7238-44f5-ae25-882ecbb56d08"),
                            Barcode = "LENT-20251113-001",
                            BorrowerFullName = "Alice Williams",
                            BorrowerRole = "Teacher",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("9e6ee2b3-f65b-4eed-99d8-9487f4855a0f"),
                            ItemName = "Wireless Mouse",
                            LentAt = new DateTime(2025, 11, 13, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            Room = "Room 101",
                            Status = "Borrowed",
                            SubjectTimeSchedule = "Faculty Meeting - Friday 3:00 PM",
                            TeacherFullName = "",
                            UserId = new Guid("4138386d-26ff-478a-b036-5d5fa6b59847")
                        },
                        new
                        {
                            Id = new Guid("631b7402-28dd-42c2-9ce9-2bdbbfcf0b82"),
                            Barcode = "LENT-20251017-001",
                            BorrowerFullName = "Bob Brown",
                            BorrowerRole = "Teacher",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("b980bd3a-a23e-4e07-aa01-1da198d14f8d"),
                            ItemName = "Mechanical Keyboard",
                            LentAt = new DateTime(2025, 10, 17, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            ReturnedAt = new DateTime(2025, 11, 1, 11, 10, 24, 58, DateTimeKind.Utc).AddTicks(9247),
                            Room = "Room 302",
                            Status = "Returned",
                            SubjectTimeSchedule = "IT Workshop - Daily",
                            TeacherFullName = "",
                            UserId = new Guid("8e270c16-b686-46c6-811e-a1729e834625")
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("721a0113-f1e7-43e3-9ffd-3b8f04c8d4b3"),
                            Email = "superadmin@example.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "$2a$11$0L7rAS7/xzqPJMl7uFNdheWyQzTNEj5l3832dgMPWU2mojEEoPT2y",
                            Status = "Offline",
                            UserRole = "SuperAdmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = new Guid("6d46b16f-00e7-4d9e-93b5-7bb7c8a17a57"),
                            Email = "admin1@example.com",
                            FirstName = "Admin1",
                            LastName = "User",
                            PasswordHash = "$2a$11$BemgpD/hHln/zTXZUaiHreoizYI8caZdgZ3aF9ZDvn0d7flilqnt.",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = new Guid("b13869ae-8afc-4c60-a34b-9a9d3898bce1"),
                            Email = "admin2@example.com",
                            FirstName = "Admin2",
                            LastName = "User",
                            PasswordHash = "$2a$11$sLHV773WDO2pQfEaQYdDQOs6YwYysr67qACfpNsE7ok8yUVMQnwBe",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = new Guid("470e3585-7444-4957-b745-777e2c824e76"),
                            Email = "admin3@example.com",
                            FirstName = "Admin3",
                            LastName = "User",
                            PasswordHash = "$2a$11$8HdNGQ4ZNGiAAZIvSHDwwOFTQDf5cAPUSZW5gDmOvn7TkZNE.R2/S",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin3"
                        },
                        new
                        {
                            Id = new Guid("65febc6f-de3a-4346-9643-0f68e362895a"),
                            Email = "admin4@example.com",
                            FirstName = "Admin4",
                            LastName = "User",
                            PasswordHash = "$2a$11$PyDvlw6Tw4n0QnQUCevtOeFUwV0pActiZuaK367kl5aZdzLXpUlzq",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin4"
                        },
                        new
                        {
                            Id = new Guid("f2758c89-3553-41e4-9f90-bd35e8988750"),
                            Email = "admin5@example.com",
                            FirstName = "Admin5",
                            LastName = "User",
                            PasswordHash = "$2a$11$ps/o2kXzsIeCQ/DXaOzWqONUkYW2LmxvS6GeWclIVNwOMm6Cu1dwG",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin5"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveStaff", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CityMunicipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveStudents", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveTeachers", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("07d32fbb-bc4f-416d-8c25-2bd7f8147be3"),
                            Email = "staff1@example.com",
                            FirstName = "Staff1",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$oqWv6owuWypslmkBP6RHaOpiSM.majtq1GXTbLU8YLOa4cDA3CJ0a",
                            PhoneNumber = "0998176543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff1",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("e8a5ed89-943f-4fa4-a5fa-a707d6f7cb29"),
                            Email = "staff2@example.com",
                            FirstName = "Staff2",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$KaiAxtOFWlRzbD/n1ttL2emeTpUqeW3GM2oHfidufZhu66d.g80sK",
                            PhoneNumber = "0998276543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff2",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("33c75f57-d1c2-47db-9856-ba5841875ae8"),
                            Email = "staff3@example.com",
                            FirstName = "Staff3",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$EZGEpECrVWAqj5li3kpltuSVJLDMI0EUWA6otbwXZwgtLPz8JMmry",
                            PhoneNumber = "0998376543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff3",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("07f9fcfb-c770-423d-b725-d7a3ccc25a09"),
                            Email = "staff4@example.com",
                            FirstName = "Staff4",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$cAMG7Ez/zCNqsUNAkBXyG.SRlntsym3PlTugrAyqC7wXSagZyMzwC",
                            PhoneNumber = "0998476543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff4",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("1cc83eec-6e2c-44c0-83de-f8486657356c"),
                            Email = "staff5@example.com",
                            FirstName = "Staff5",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$zFUj4Pr3jGGen05cyr6my.fX8msuhZv98SkiB0LNifPcUL.iF7Vg.",
                            PhoneNumber = "0998576543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff5",
                            Position = "Lab Technician"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("StudentIdNumber")
                        .IsUnique()
                        .HasFilter("([StudentIdNumber] IS NOT NULL AND [StudentIdNumber] <> '')");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2535298c-1b8c-4039-9b4e-17cf84b36249"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$7CKvv5ub7pw8S3qL0EpKVeHuOJs1lKfFGmoOPMLC/jlcWSsYsLA62",
                            PhoneNumber = "0912134567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "johndoe",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "S2021-001",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("14bb9ebd-6e42-40c8-bde4-f5f63a80e3b8"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$K8wjk6kI3nTS332OyLKakeoAAdipYgcy/mbXRD9lWqezybGRmfAcm",
                            PhoneNumber = "0912234567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "janesmith",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "S2021-002",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("22716e25-502a-47c5-bd3a-8563abcd7fb1"),
                            Email = "peter.jones@example.com",
                            FirstName = "Peter",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$H5Ql3QGCoLO9O4fq2j7jEuNDElbdE1EqEzgszWlIWuyvhJ2Wjv2wG",
                            PhoneNumber = "0912334567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "peterjones",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "S2021-003",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("b3b23e69-0eea-48a6-850b-46896d2ba01a"),
                            Email = "student4@example.com",
                            FirstName = "Student4",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$loy07UpnNhv9O.brDLBpD.caa0UzDjNzAZK4lhp7m5mBrluOErKF6",
                            PhoneNumber = "0912434567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student4",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "2023-0004",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("6102bd48-2531-4e41-94f4-22b8fe798438"),
                            Email = "student5@example.com",
                            FirstName = "Student5",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$ZeOkr6/Iu8s9AVq.Gmj8D.vO1SOtKnZ.OyF/EaYvM1By.ZE3H8SNi",
                            PhoneNumber = "0912534567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student5",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "2023-0005",
                            Year = "3"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4138386d-26ff-478a-b036-5d5fa6b59847"),
                            Email = "alice.williams@example.com",
                            FirstName = "Alice",
                            LastName = "Williams",
                            PasswordHash = "$2a$11$eKsLGVYwlQQdTFFUUYQvHe1Gli4kxBzyacBWpC8KqpohyHaDmR3hm",
                            PhoneNumber = "0917123456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "alicewilliams",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("8e270c16-b686-46c6-811e-a1729e834625"),
                            Email = "bob.brown@example.com",
                            FirstName = "Bob",
                            LastName = "Brown",
                            PasswordHash = "$2a$11$WD36frkqXzdnGvUVNkVoze7O4oM/dVkfEOLq6sN/arEWgk0eMmCyu",
                            PhoneNumber = "0917223456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "bobbrown",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("dd4c3ad1-0473-41eb-8f2c-6b4c7181e192"),
                            Email = "teacher3@example.com",
                            FirstName = "Teacher3",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$WXbqkJgdbDXHLq9q1fR9POdMBTm4brS7x2ZbcQrBSItCO3EftvNp6",
                            PhoneNumber = "0917323456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher3",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("88a2c501-a016-41d0-b62b-c7375f6f5cc2"),
                            Email = "teacher4@example.com",
                            FirstName = "Teacher4",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$L/GJMBryC/4okqpW2fobNOfDLCZxg3Gy8mBKGB2w3mNR3UjtZgO26",
                            PhoneNumber = "0917423456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher4",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("bddf357e-9c3d-486c-9ded-5fc75c0344ed"),
                            Email = "teacher5@example.com",
                            FirstName = "Teacher5",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$ItgFyyqu2r3xg5J3y5zvku1n6HlwQywAf3BZimzfqvOrM.WGV3aum",
                            PhoneNumber = "0917523456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher5",
                            Department = "Information Technology"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("LentItems")
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Staff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Navigation("LentItems");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
