// <auto-generated />
using System;
using BackendTechnicalAssetsManagement.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendTechnicalAssetsManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251007000235_AddArchiveItemsEntity")]
    partial class AddArchiveItemsEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ArchiveItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6524a65c-9195-4132-9a21-86b6151feb60"),
                            Category = "Electronics",
                            Condition = "New",
                            CreatedAt = new DateTime(2025, 10, 7, 0, 2, 34, 228, DateTimeKind.Utc).AddTicks(8625),
                            Description = "High-performance laptop for students.",
                            ItemMake = "Dell",
                            ItemModel = "XPS 15",
                            ItemName = "Laptop",
                            ItemType = "Electronic",
                            SerialNumber = "SN123456",
                            UpdatedAt = new DateTime(2025, 10, 7, 0, 2, 34, 228, DateTimeKind.Utc).AddTicks(8625)
                        },
                        new
                        {
                            Id = new Guid("982cdd99-0219-4508-a342-6d55056ef784"),
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 7, 0, 2, 34, 228, DateTimeKind.Utc).AddTicks(8634),
                            Description = "Portable projector for classroom use.",
                            ItemMake = "Epson",
                            ItemModel = "PowerLite 1781W",
                            ItemName = "Projector",
                            ItemType = "Electronic",
                            SerialNumber = "SN654321",
                            UpdatedAt = new DateTime(2025, 10, 7, 0, 2, 34, 228, DateTimeKind.Utc).AddTicks(8635)
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("LentItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98129664-1245-47ec-ba29-c479f2113665"),
                            BorrowerFullName = "Peter Jones",
                            BorrowerRole = "Student",
                            ItemId = new Guid("6524a65c-9195-4132-9a21-86b6151feb60"),
                            LentAt = new DateTime(2025, 10, 7, 0, 2, 34, 228, DateTimeKind.Utc).AddTicks(8725),
                            Remarks = "Borrowed",
                            Room = "Room 101",
                            StudentIdNumber = "2023-0001",
                            SubjectTimeSchedule = "MWF 10:00-11:00 AM",
                            TeacherFullName = "Mary Williams",
                            TeacherId = new Guid("6d91578b-2030-4c59-934e-4415f9d326ab"),
                            UserId = new Guid("0a6dfab6-b88c-4038-a2e0-afecb682ee8d")
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Admin", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Admins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("64e0d350-8f60-4455-9f84-99136f526fa5"),
                            Email = "superadmin@example.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEMUVt1ZKxWf3yedhOzHilgy8jVbqk11hok/ewXg9v1/SWkx0yMxBMvD1w+Ctr3I9tA==",
                            Status = "",
                            UserRole = "SuperAdmin",
                            Username = "superadmin",
                            PhoneNumber = "999-999-9999"
                        },
                        new
                        {
                            Id = new Guid("55393592-65bb-4df2-bcc8-8e8225f8732e"),
                            Email = "admin@gmail.com",
                            FirstName = "admin",
                            LastName = "admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEAG9aonrSvffnOZuk9v03IZTya/FSV9dRQb+4Mv/IcgpNGD455gn257OsV81fhD9hg==",
                            Status = "",
                            UserRole = "Admin",
                            Username = "admin",
                            PhoneNumber = "123-456-7890"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("94fd2f53-95e8-4782-82ac-a364942a4c84"),
                            Email = "staff@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "AQAAAAIAAYagAAAAEHLgdQ8CVwSCsQnhQsC7JTMec7cZuI0J14JfGeQ4bggb4zR78hiKNmXmhFQHk2P3kg==",
                            Status = "",
                            UserRole = "Staff",
                            Username = "staff",
                            PhoneNumber = "098-765-4321",
                            Position = "Lab Technician"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a6dfab6-b88c-4038-a2e0-afecb682ee8d"),
                            Email = "student@example.com",
                            FirstName = "Peter",
                            LastName = "Jones",
                            PasswordHash = "AQAAAAIAAYagAAAAEAqak473FFcxcRYRA/YZ8FHjXjMDvstvWropMcXMnJjED4hcYRpYmhO3ePUgqkkKZQ==",
                            Status = "",
                            UserRole = "Student",
                            Username = "student",
                            CityMunicipality = "Anytown",
                            Course = "Computer Science",
                            PhoneNumber = "555-123-4567",
                            PostalCode = "12345",
                            Province = "Anyprovince",
                            Section = "A",
                            Street = "123 Main St",
                            StudentIdNumber = "2023-0001",
                            Year = "3"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d91578b-2030-4c59-934e-4415f9d326ab"),
                            Email = "teacher@example.com",
                            FirstName = "Mary",
                            LastName = "Williams",
                            PasswordHash = "AQAAAAIAAYagAAAAENJubTz/gJibKZsciCUNdXhN0cC66jDetcO69NcOO5TOztgkf40lyENPxOh20LAgPw==",
                            Status = "",
                            UserRole = "Teacher",
                            Username = "teacher",
                            Department = "Information Technology",
                            PhoneNumber = "555-987-6543"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Admin", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Staff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
