// <auto-generated />
using System;
using BackendTechnicalAssetsManagement.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendTechnicalAssetsManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251029141812_RemoveItemIdFromArchiveItems")]
    partial class RemoveItemIdFromArchiveItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ArchiveItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("ArchiveLentItems");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OriginalUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserRole")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArchiveUsers");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f19c228-c324-47e1-aa6b-46aa6f68a98e"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 29, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(7954),
                            Description = "High-performance laptop for video editing.",
                            ItemMake = "Dell",
                            ItemModel = "XPS 15 9510",
                            ItemName = "Dell XPS 15 Laptop",
                            ItemType = "Laptop",
                            SerialNumber = "SN-LP-DELL-001",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 29, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(7955)
                        },
                        new
                        {
                            Id = new Guid("6331053f-c190-476f-8e08-01d44b3650a4"),
                            Category = "MediaEquipment",
                            Condition = "New",
                            CreatedAt = new DateTime(2025, 10, 29, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(7960),
                            Description = "1080p projector for classroom presentations.",
                            ItemMake = "Epson",
                            ItemModel = "HC 2250",
                            ItemName = "Epson Home Cinema Projector",
                            ItemType = "Projector",
                            SerialNumber = "SN-PR-EPS-002",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 29, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(7961)
                        },
                        new
                        {
                            Id = new Guid("2e41a6e8-1b80-4756-a204-5ecde0ad6fb6"),
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 29, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(7966),
                            Description = "Full-frame mirrorless camera with 4K video.",
                            ItemMake = "Canon",
                            ItemModel = "EOS R6",
                            ItemName = "Canon EOS R6 Camera",
                            ItemType = "Camera",
                            SerialNumber = "SN-CM-CAN-003",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 29, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(7967)
                        },
                        new
                        {
                            Id = new Guid("1a512806-4072-4749-8c60-fed2e7456cb8"),
                            Category = "MediaEquipment",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 29, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(7973),
                            Description = "Dynamic microphone for vocal recording.",
                            ItemMake = "Shure",
                            ItemModel = "SM7B",
                            ItemName = "Shure SM7B Microphone",
                            ItemType = "Microphone",
                            SerialNumber = "SN-MC-SHR-004",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 29, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(7974)
                        },
                        new
                        {
                            Id = new Guid("9f078b90-1140-4932-8fb7-dfed46541540"),
                            Category = "Electronics",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 10, 29, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(7983),
                            Description = "Tablet for digital art and design classes.",
                            ItemMake = "Apple",
                            ItemModel = "iPad Pro 12.9-inch",
                            ItemName = "Apple iPad Pro",
                            ItemType = "Tablet",
                            SerialNumber = "SN-TB-APL-005",
                            Status = "Available",
                            UpdatedAt = new DateTime(2025, 10, 29, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(7986)
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("BarcodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BorrowerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHiddenFromUser")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTimeSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("LentItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c56f51db-ef35-4cc8-9b52-59bda7896aa1"),
                            BorrowerFullName = "John Doe",
                            BorrowerRole = "Student",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("7f19c228-c324-47e1-aa6b-46aa6f68a98e"),
                            ItemName = "Dell XPS 15 Laptop",
                            LentAt = new DateTime(2025, 10, 24, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(8712),
                            Room = "",
                            Status = "Borrowed",
                            StudentIdNumber = "S2021-001",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "Alice Williams",
                            TeacherId = new Guid("d82702b6-8326-466e-8083-ad55a9b1e03a"),
                            UserId = new Guid("333a16d4-02f9-457b-bd42-4fbb972fd5fb")
                        },
                        new
                        {
                            Id = new Guid("4fd60aec-0b5d-42d9-a65f-972122aff81a"),
                            BorrowerFullName = "Jane Smith",
                            BorrowerRole = "Student",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("2e41a6e8-1b80-4756-a204-5ecde0ad6fb6"),
                            ItemName = "Canon EOS R6 Camera",
                            LentAt = new DateTime(2025, 10, 19, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(8734),
                            ReturnedAt = new DateTime(2025, 10, 27, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(8735),
                            Room = "",
                            Status = "Returned",
                            StudentIdNumber = "S2021-002",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "Bob Brown",
                            TeacherId = new Guid("a5bce19e-4c57-45cb-aca7-db7625a0c112"),
                            UserId = new Guid("fe790f52-f317-45e9-a8b0-5858a7aa66dd")
                        },
                        new
                        {
                            Id = new Guid("eb2337a8-e9d5-4474-87dd-01cac3a4e330"),
                            BorrowerFullName = "Peter Jones",
                            BorrowerRole = "Student",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("6331053f-c190-476f-8e08-01d44b3650a4"),
                            ItemName = "Epson Home Cinema Projector",
                            LentAt = new DateTime(2025, 10, 28, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(8748),
                            Room = "",
                            Status = "Borrowed",
                            StudentIdNumber = "S2021-003",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "Alice Williams",
                            TeacherId = new Guid("d82702b6-8326-466e-8083-ad55a9b1e03a"),
                            UserId = new Guid("a02f3fa3-3add-441e-959a-b2cad649d164")
                        },
                        new
                        {
                            Id = new Guid("d7e847fe-e4b2-407d-9f34-051a34f9e915"),
                            BorrowerFullName = "Alice Williams",
                            BorrowerRole = "Teacher",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("1a512806-4072-4749-8c60-fed2e7456cb8"),
                            ItemName = "Shure SM7B Microphone",
                            LentAt = new DateTime(2025, 10, 26, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(8756),
                            Room = "",
                            Status = "Borrowed",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "",
                            UserId = new Guid("d82702b6-8326-466e-8083-ad55a9b1e03a")
                        },
                        new
                        {
                            Id = new Guid("b7d644f0-727f-4311-9973-d16f06bd9ba1"),
                            BorrowerFullName = "Bob Brown",
                            BorrowerRole = "Teacher",
                            IsHiddenFromUser = false,
                            ItemId = new Guid("9f078b90-1140-4932-8fb7-dfed46541540"),
                            ItemName = "Apple iPad Pro",
                            LentAt = new DateTime(2025, 9, 29, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(8771),
                            ReturnedAt = new DateTime(2025, 10, 14, 14, 18, 11, 613, DateTimeKind.Utc).AddTicks(8772),
                            Room = "",
                            Status = "Returned",
                            SubjectTimeSchedule = "",
                            TeacherFullName = "",
                            UserId = new Guid("a5bce19e-4c57-45cb-aca7-db7625a0c112")
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("32f0c9e7-c19a-492d-b1d8-083e7ca1f43f"),
                            Email = "superadmin@example.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "$2a$11$SufLjpayC//YRa5PsVAryOgksALNhgGfGlLN6iz8tQM1R6hnzGSEK",
                            Status = "Offline",
                            UserRole = "SuperAdmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = new Guid("99f7870c-0603-4b93-ac7a-eed3315ca07a"),
                            Email = "admin1@example.com",
                            FirstName = "Admin1",
                            LastName = "User",
                            PasswordHash = "$2a$11$8fZWemky4kkBiV18.npA8uiJyA5Ox4X1jaD/shPpwet3R85k0Bg96",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = new Guid("7a1afac4-0933-467f-a099-21f59c7f0adb"),
                            Email = "admin2@example.com",
                            FirstName = "Admin2",
                            LastName = "User",
                            PasswordHash = "$2a$11$sQ1quNVlLCsRh4I5ISMpGur6otCobchuRmTRvy8bG1FEqR9nbb8NO",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = new Guid("de880717-2d07-49eb-a609-de246068c28c"),
                            Email = "admin3@example.com",
                            FirstName = "Admin3",
                            LastName = "User",
                            PasswordHash = "$2a$11$i7kTO0F6dtCiLRSpT9foxutKefHqVvt4MMOkA4AfkO.rhEaGOkkli",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin3"
                        },
                        new
                        {
                            Id = new Guid("2250b3a5-8c28-4c9d-a725-7c96b4fa3ec5"),
                            Email = "admin4@example.com",
                            FirstName = "Admin4",
                            LastName = "User",
                            PasswordHash = "$2a$11$tJnyg2e.lJ1RJMhP5h4nJO/F4spVe0Nf/PReM91v7ted9URJQY1eS",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin4"
                        },
                        new
                        {
                            Id = new Guid("34cbe681-2c94-46e1-9ff4-3b3eb5cb033a"),
                            Email = "admin5@example.com",
                            FirstName = "Admin5",
                            LastName = "User",
                            PasswordHash = "$2a$11$hXLxK/Te48WpM0bxtdMSjOUF4rAbCvTYVa8cQVMoxZopi4QxMAp5u",
                            Status = "Offline",
                            UserRole = "Admin",
                            Username = "admin5"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveStaff", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CityMunicipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveStudents", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArchiveTeachers", (string)null);
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff8f0411-1b61-4223-bfba-1d23c24e571a"),
                            Email = "staff1@example.com",
                            FirstName = "Staff1",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$dyS0G2jGnwgHuxFaASoY7uyO4hCA39qJV8FZ0Xm8Bjt0P/SEB12cK",
                            PhoneNumber = "0998176543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff1",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("a918b1ee-f128-4233-929f-df631ef843b4"),
                            Email = "staff2@example.com",
                            FirstName = "Staff2",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$y4HPXM46dADD5eQddoMaJu08WDHcLfumrvvijoHs.mei.WeUMIEvW",
                            PhoneNumber = "0998276543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff2",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("1fa15a68-cb7a-4797-9a59-57b68edb4a6e"),
                            Email = "staff3@example.com",
                            FirstName = "Staff3",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$AOK3bTJ1pRRc0MUCKRt/o.fqyElsVoYe5ynyDI.Q3V0zu/jVqJnhi",
                            PhoneNumber = "0998376543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff3",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("7ce158ee-72a7-44d0-b0fc-40234fac7b75"),
                            Email = "staff4@example.com",
                            FirstName = "Staff4",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$pmlpUxzsJX/8aX6MEk6w1ex/TZD39LfGPG31W5wsD8GEJW0vYn/sW",
                            PhoneNumber = "0998476543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff4",
                            Position = "Lab Technician"
                        },
                        new
                        {
                            Id = new Guid("f3678581-4513-46fe-8e2d-e9c4059ddcc2"),
                            Email = "staff5@example.com",
                            FirstName = "Staff5",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$t90TbbTTdyi9qctP.AG/xOkpW6el/iKaIagmYmtAk3M0Wupd4hXPW",
                            PhoneNumber = "0998576543",
                            Status = "Offline",
                            UserRole = "Staff",
                            Username = "staff5",
                            Position = "Lab Technician"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<byte[]>("BackStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FrontStudentIdPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("StudentIdNumber")
                        .IsUnique()
                        .HasFilter("([StudentIdNumber] IS NOT NULL AND [StudentIdNumber] <> '')");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("333a16d4-02f9-457b-bd42-4fbb972fd5fb"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$11$m2Lfj2TQkalHmXtxUq9MaOtyHmahBGuZXulDclD/JGUpiBBNChUdG",
                            PhoneNumber = "0912134567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "johndoe",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "S2021-001",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("fe790f52-f317-45e9-a8b0-5858a7aa66dd"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$jf7l6Mzm6Imhpz1bWmkNjumgLcJ/ScqvlMCKHD0FrqeHJZW2Qmcuy",
                            PhoneNumber = "0912234567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "janesmith",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "S2021-002",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("a02f3fa3-3add-441e-959a-b2cad649d164"),
                            Email = "peter.jones@example.com",
                            FirstName = "Peter",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$lwShbvU23bsf8zen1YFHk.qQGNZppZiDMTW.ucbpF1e18Z/GAzEsy",
                            PhoneNumber = "0912334567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "peterjones",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "S2021-003",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("af6bf375-ecd6-49f5-bfc9-711d1cf18c12"),
                            Email = "student4@example.com",
                            FirstName = "Student4",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$qLgfIV6GGIIqtC4geDiXrud2QDU8khgQO84aRN60TD/MvzP..lGJS",
                            PhoneNumber = "0912434567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student4",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "2023-0004",
                            Year = "3"
                        },
                        new
                        {
                            Id = new Guid("34acfc5d-c3dd-4e57-943b-b2b00be3662c"),
                            Email = "student5@example.com",
                            FirstName = "Student5",
                            LastName = "Jones",
                            PasswordHash = "$2a$11$XpzmesGDYAbE/e7Dm1VApemGgLKibz0zopznf79kcvqkaCnuVzgmC",
                            PhoneNumber = "0912534567",
                            Status = "Offline",
                            UserRole = "Student",
                            Username = "student5",
                            CityMunicipality = "",
                            Course = "Computer Science",
                            PostalCode = "",
                            Province = "",
                            Section = "A",
                            Street = "",
                            StudentIdNumber = "2023-0005",
                            Year = "3"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasBaseType("BackendTechnicalAssetsManagement.src.Classes.User");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d82702b6-8326-466e-8083-ad55a9b1e03a"),
                            Email = "alice.williams@example.com",
                            FirstName = "Alice",
                            LastName = "Williams",
                            PasswordHash = "$2a$11$RUEnQy6SKQkFOIJKFmTyVeSQZsKGEuJjXsFY38wDYuzqnKSp6hNjO",
                            PhoneNumber = "0917123456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "alicewilliams",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("a5bce19e-4c57-45cb-aca7-db7625a0c112"),
                            Email = "bob.brown@example.com",
                            FirstName = "Bob",
                            LastName = "Brown",
                            PasswordHash = "$2a$11$/e2KPmi3QZ0/eE7vs67rAel2NwcV1U4gnjdOPvRCj4h2nbs/JNNcu",
                            PhoneNumber = "0917223456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "bobbrown",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("244773dd-5ac9-4cc3-8b29-89e7185c82cc"),
                            Email = "teacher3@example.com",
                            FirstName = "Teacher3",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$ucpDpm2naJn3Yix6xTklu.83.56pfkfQK.KPIqf7d9wXcpdMuci0m",
                            PhoneNumber = "0917323456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher3",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("08efd894-7889-48f1-9c29-d8541eb828f7"),
                            Email = "teacher4@example.com",
                            FirstName = "Teacher4",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$dXfM6jqpqV5SVEOsBSGB4OlJK.5ApWSQlHMSYz9Vfk5hj3NlLCDzi",
                            PhoneNumber = "0917423456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher4",
                            Department = "Information Technology"
                        },
                        new
                        {
                            Id = new Guid("ffde25a6-29aa-4a75-aa35-a5ba3d5bd74a"),
                            Email = "teacher5@example.com",
                            FirstName = "Teacher5",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$J4Gs9.KIXb8fLee8guRU/e4Ek1kBoBSSVtlFn0JaupeER6YPqdTVq",
                            PhoneNumber = "0917523456",
                            Status = "Offline",
                            UserRole = "Teacher",
                            Username = "teacher5",
                            Department = "Information Technology"
                        });
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveLentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.LentItems", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("LentItems")
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.RefreshToken", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveStaff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveStudent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.ArchiveUser", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.ArchiveTeacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Staff", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Staff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Student", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.Teacher", b =>
                {
                    b.HasOne("BackendTechnicalAssetsManagement.src.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("BackendTechnicalAssetsManagement.src.Classes.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTechnicalAssetsManagement.src.Classes.User", b =>
                {
                    b.Navigation("LentItems");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
